name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: pytest

    - name: Open Pull Request (on success)
      if: success()
      run: gh pr create --base main --head dev-branch --title "Automated Pull Request - Successful Build"


  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8


    - name: Grant Execute Permissions to deploy.sh
      run: |
        chmod +x deploy.sh

    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
        ./deploy.sh
